LIB        = libdavinci.a

SRCS       = \
         DaVinciGraphTerm.hs\
         DaVinciEvent.hs\
         DaVinciActions.hs\
         DaVinciCore.hs\
         DaVinciMenu.hs\
         DaVinciIcon.hs\
         DaVinciClasses.hs\
         DaVinciNodeType.hs\
         DaVinciEdgeType.hs\
         DaVinciRules.hs\
         DaVinciGraph.hs\
         DaVinciNode.hs\
         DaVinciEdge.hs\
         DaVinciDragAndDrop.hs\
         DaVinciSelection.hs\
         DaVinciView.hs\
         DaVinciPopupMenu.hs\
         DaVinci.hs\
         DaVinciGraphDisp.hs\
#        WidgetTreeView.hs\
#        GraphEditor.hs\

SUBDIRS = test

XHCDIRS = $(HTKDIRS)

include top/mk/boilerplate.mk
