LIB        = libdavinci.a

SRCS       = \
         DaVinciGraphTerm.hs\
	 DaVinciEvent.hs\
	 DaVinciCore.hs\
	 DaVinciMenu.hs\
	 DaVinciIcon.hs\
	 DaVinciClasses.hs\
	 DaVinciNodeType.hs\
	 DaVinciEdgeType.hs\
	 DaVinciRules.hs\
	 DaVinciGraph.hs\
	 DaVinciNode.hs\
	 DaVinciEdge.hs\
	 DaVinciDragAndDrop.hs\
	 DaVinciSelection.hs\
	 DaVinciView.hs\
	 DaVinciPopupMenu.hs\
	 DaVinci.hs\
	 WidgetTreeView.hs\
	 GraphEditor.hs\

SUBDIRS = test

include top/mk/boilerplate.mk
