LIBS       = $(TOOLSDIR)/libtools.a\
	     $(HTKDIR)/libhtk.a\
	     $(REACTORDIR)/libreactor.a\
	     $(CONCDIR)/libconcurrency.a\
	     $(UTILDIR)/libutil.a\

SRCS = Test3.hs TestDiff.hs TestGrep.hs TestHolCSP.hs TestHolZ.hs TestHugs1.hs TestHugs2.hs TestLatex.hs TestMoby.hs TestTextEdit.hs

include top/mk/boilerplate.mk




# DO NOT DELETE: Beginning of Haskell dependencies
Test3.o : Test3.hs
Test3.o : top/tools/WB.hi
Test3.o : top/tools/Tas.hi
Test3.o : top/util/Debug.hi
TestDiff.o : TestDiff.hs
TestDiff.o : top/tools/WB.hi
TestDiff.o : top/tools/Diff.hi
TestDiff.o : top/util/Debug.hi
TestGrep.o : TestGrep.hs
TestGrep.o : top/tools/WB.hi
TestGrep.o : top/tools/Grep.hi
TestGrep.o : top/util/Debug.hi
TestHolCSP.o : TestHolCSP.hs
TestHolCSP.o : top/tools/WB.hi
TestHolCSP.o : top/tools/HolCSP.hi
TestHolCSP.o : top/util/Debug.hi
TestHolZ.o : TestHolZ.hs
TestHolZ.o : top/tools/WB.hi
TestHolZ.o : top/tools/HolZ.hi
TestHolZ.o : top/util/Debug.hi
TestHugs1.o : TestHugs1.hs
TestHugs1.o : top/tools/WB.hi
TestHugs1.o : top/tools/Hugs.hi
TestHugs1.o : top/util/Debug.hi
TestHugs2.o : TestHugs2.hs
TestHugs2.o : top/tools/WB.hi
TestHugs2.o : top/tools/Hugs.hi
TestHugs2.o : top/util/Debug.hi
TestLatex.o : TestLatex.hs
TestLatex.o : top/tools/WB.hi
TestLatex.o : top/tools/Latex.hi
TestLatex.o : top/tools/Dvips.hi
TestLatex.o : top/htk/toolkit/DialogWin.hi
TestLatex.o : top/util/Debug.hi
TestMoby.o : TestMoby.hs
TestMoby.o : top/tools/WB.hi
TestMoby.o : top/tools/Moby.hi
TestMoby.o : top/util/Debug.hi
TestTextEdit.o : TestTextEdit.hs
TestTextEdit.o : top/tools/WB.hi
TestTextEdit.o : top/util/Debug.hi
# DO NOT DELETE: End of Haskell dependencies
