LIBS = $(UNIDIR)/tools/libtools.a $(UNIDIR)/htk/libhtk.a \
   $(UNIDIR)/reactor/libreactor.a $(UNIDIR)/concurrency/libconcurrency.a \
   $(UNIDIR)/util/libutil.a 

SRCS = Test3.hs TestDiff.hs TestGrep.hs TestHolZ.hs TestHugs1.hs TestHugs2.hs TestLatex.hs TestMoby.hs TestTextEdit.hs 
# TestHolCSP.hs 

include top/mk/boilerplate.mk
