LIBS = $(UNIDIR)/htk/libhtk.a $(UNIDIR)/reactor/libreactor.a\
   $(UNIDIR)/concurrency/libconcurrency.a $(UNIDIR)/util/libutil.a

SRCS       = MainfileBrowserTest.hs MainfileBrowser.hs MaintreeDrawTest.hs MainiconsDrawTest.hs

XHCDIRS = $(HTKDIRS)

include top/mk/boilerplate.mk



