LIBS = $(UNIDIR)/htk/libhtk.a $(UNIDIR)/reactor/libreactor.a\
   $(UNIDIR)/concurrency/libconcurrency.a $(UNIDIR)/util/libutil.a

SRCS       = MaintreeDrawTest.hs MainfileBrowserTest.hs MainiconsDrawTest.hs

XHCDIRS = $(HTKDIRS)

include top/mk/boilerplate.mk



