#! /usr/local/bin/bash
# This script should be run in cygwin in the uni directory.  However it
# doesn't assume ghc is cygwin-aware.

GCC=gcc
GHC=ghc
MAKE=make
FIND=find
CP=cp
AR=ar

if [ -z $SKIPCOMPILE ]
then

if [ -z $SKIPINTRO ]
then


./configure

# Do the C files
$GHC -Iincludes -c util/default_options.c
$GHC -Iincludes -c util/new_object.c
$GHC -Iincludes -c windows/runWish.c

mk/mkEverything `$MAKE displayhtkhs -s --no-print-directory`

fi

IMPORTS=`cygpath -awp windows:util:events:reactor:htk/kernel:htk/canvasitems:htk/components:htk/containers:htk/devices:htk/menuitems:htk/packer:htk/resources:htk/textitems:htk/tix:htk/toolkit:htk/toplevel:htk/widgets`
echo $IMPORTS

$GHC --make EVERYTHING.hs -package concurrent -package data -package text -package lang -fglasgow-exts -fallow-overlapping-instances -fallow-undecidable-instances -cpp -i"$IMPORTS" -Iincludes -O

mkdir -p imports
fi

$CP `$FIND . -name "*.hi"` imports
$AR -r libhtkwin.a `$FIND . -name "*.o"`
