#!/bin/sh
# 
# Pass a file to MMiSS checker.
# 
# Argument 1 = working directory
# Argument 2 = name of XML file
#

`dirname $0`/../checker/bin/mmiss-checker $1/$2 

# echo '
# <checklist>
#   <check name="Occurence check" success="Yes"></check>
#   <check name="Cyclic definitions" success="No">
#          <message>All your definitions are rubbish!</message>
#          <mmissobject id="7585"/><mmissobject id="2070498"/>
#   </check>
# </checklist>
# '
