#!/bin/sh
#pkill Coupling
ln -sf ../CouplingServer CouplingTestServer
cd `dirname $0`
UNISERVERDIR=`pwd`
export UNISERVERDIR
./CouplingTestServer --uni-server=localhost --uni-port=11393 --uni-couplingDir=/home/amahnke/sfb/test/coupling | tee -a coupling.log &
# ../testCouplingServer -port=11391
