PACKAGES = uni-util uni-posixutil uni-davinci uni-htk fgl text lang-1.0
PACKAGE = uni-ontology

SRCS = AbstractGraphView.hs MMiSSOntology.hs MMiSSOntologyGraph.hs OntoParser.hs MainOntoTool.hs

XHCDIRS= $(HTKDIRS)

EXTRA_HC_OPTIONS = -ignore-package uni-mmiss -ignore-package uni-mmiss-parser

include /home/amahnke/uni/mk/boilerplate.mk

