LIBS = $(UNIDIR)/www/libwww.a $(UNIDIR)/htk/libhtk.a \
    $(UNIDIR)/reactor/libreactor.a $(UNIDIR)/concurrency/libconcurrency.a \
    $(UNIDIR)/util/libutil.a

SRCS = Test1.hs

include top/mk/boilerplate.mk



