LIBS       = $(WWWDIR)/libwww.a\
	     $(HTKDIR)/libhtk.a\
	     $(REACTORDIR)/libreactor.a\
	     $(CONCDIR)/libconcurrency.a\
	     $(UTILDIR)/libutil.a

SRCS = Test1.hs

include top/mk/boilerplate.mk



