#!/bin/sh
cd `dirname $0`
pkill MMiSSAPITestServer
rm -rf MMiSSAPITestServer
ln -sf ../MMiSSServer MMiSSAPITestServer
UNISERVERDIR=`pwd`
UNISERVER=localhost
UNIXMLPORT=11397
UNITOP=`pwd | sed -e s+/mmiss/api/dummyserver$++`
export UNISERVERDIR UNISERVER UNIXMLPORT UNITOP
./MMiSSAPITestServer &
../testMMiSSServer
