LIB        = libversions.a
SRCS       = VersionDB.hs UniTypes.hs FileSys.hs Graph.hs SharedGraph.hs \
   SharedGraphService.hs SharedGraphClient.hs
SUBDIRS    = test

include top/mk/boilerplate.mk








