LIBS       = $(HTKDIR)/libhtk.a\
	     $(REACTORDIR)/libreactor.a\
	     $(CONCDIR)/libconcurrency.a\
	     $(UTILDIR)/libutil.a

SRCS = Test1.hs Test2.hs Test3.hs Test9.hs Test10.hs TestBug3.hs Counter.hs Util.hs

LIB = libhtkTest.a

include top/mk/boilerplate.mk
