LIBS = $(UNIDIR)/htk/libhtk.a $(UNIDIR)/reactor/libreactor.a\
    $(UNIDIR)/concurrency/libconcurrency.a $(UNIDIR)/util/libutil.a

SRCS = Test1.hs Test2.hs Test3.hs Test9.hs Test10.hs TestBug3.hs Counter.hs Util.hs

LIB = libhtkTest.a

XHCDIRS = $(HTKDIRS)

include top/mk/boilerplate.mk
