#!/bin/sh
set -e
# Test for .elc files omitted since (1) Workbench checks it can talk to XEmacs
# when it starts up anyway; (2) .el files are also OK.
# if [ ! \( -r $TOP/emacs/sendmess.elc -a -r $TOP/emacs/allmmiss.elc -a -r $TOP/emacs/extents.elc -a -r $TOP/emacs/mmisstex.elc \) ]
# then
# echo Emacs bytecode in $TOP/emacs must be compiled first!!
# exit 16
# fi

if [ ! -r $TOP/posixutil/runCommand ]
then
echo "runCommand" in $TOP/posixutil must be compiled first!!
exit 16
fi