#!/bin/sh
set -e
if [ ! \( -r $TOP/emacs/sendmess.elc -a -r $TOP/emacs/allmmiss.elc -a -r $TOP/emacs/extents.elc -a -r $TOP/emacs/mmisstex.elc \) ]
then
echo Emacs bytecode in $TOP/emacs must be compiled first!!
exit 16
fi

if [ ! -r $TOP/posixutil/runCommand ]
then
echo "runCommand" in $TOP/posixutil must be compiled first!!
exit 16
fi