#!/usr/local/bin/bash
export CVSROOT=/home/uniform/backup/repository
rm -rf A B 1 2 3 4
pkill -x allocate
pkill -x server
rm -rf /home/uniform/backup/repository/db
mkdir /home/uniform/backup/repository/db
/home/ger/uni/concurrency/server/server &
/home/ger/uni/cvs/inodeserver/allocate &
/home/ger/uni/versions/test/test1
