#!/usr/local/bin/bash
# Test script for running the workbench.
export UNISERVER=`hostname`
export UNIEDITOR="/usr/local/pub-bkb/xemacs/bin/gnuclient -eval '(setq stored-name \"%beN\")' \"%bF\""
gmake killServer
gmake killWorkbench
gmake runServer
gmake runWorkbench
