#!/usr/local/bin/bash
# Test script for running the workbench.
rm -rf /home/ger/repository/db/*,v GraphEditor.backup VersionGraph.backup
export UNICVSROOT=/home/ger/repository
export UNISERVER=`hostname`
export UNIEDITOR="gnuclient -eval '(setq stored-name \"%beN\")' \"%bF\""
pkill -x Server
rm -rf /tmp/db
export UNIDEBUG=/home/ger/uni/types/test/s.debug
./Server &
export UNIDEBUG=/home/ger/uni/types/test/w.debug
./Workbench