LIBS = $(UNIDIR)/concurrency/libconcurrency.a $(UNIDIR)/util/libutil.a

LIB = libserver.a

SRCS       = ServiceClass.hs Server.hs Testserver.hs EchoService.hs \
# CallServer.hs is now part of the reactor.

include top/mk/boilerplate.mk
