LIBS = $(UNIDIR)/concurrency/libconcurrency.a $(UNIDIR)/util/libutil.a

LIB = libserver.a

SRCS       = ServiceClass.hs Server.hs Testserver.hs CallServer.hs EchoService.hs \

include top/mk/boilerplate.mk
