HCINC      =

IMPS	   = *.hi

LIBS       =

THIS	   = util

LIB        = libutil.a

SRCS       = Queue.hs ExtendedPrelude.hs Computation.hs Dynamics.hs WBFiles.hs Object.hs Date.hs Debug.hs Maybes.hs
  
SRCSH      = 
SRCSC      = 

PGMS       = 
PGM_OBJS   = 
EXTRA_DEPS = 


EXTRA_HC_OPTIONS += -O -H30M

include top/mk/boilerplate.mk
















# DO NOT DELETE: Beginning of Haskell dependencies
Queue.o : Queue.hs
Queue.o : ./Maybes.hi
Queue.o : ./Debug.hi
ExtendedPrelude.o : ExtendedPrelude.hs
ExtendedPrelude.o : ./Debug.hi
Computation.o : Computation.hs
Computation.o : ./Maybes.hi
Computation.o : ./Debug.hi
Dynamics.o : Dynamics.hs
Dynamics.o : ./Debug.hi
WBFiles.o : WBFiles.hs
WBFiles.o : ./Debug.hi
Object.o : Object.hs
Object.o : ./Computation.hi
Object.o : ./Debug.hi
Date.o : Date.hs
Date.o : ./Debug.hi
Debug.o : Debug.hs
Maybes.o : Maybes.hs
Maybes.o : ./Debug.hi
# DO NOT DELETE: End of Haskell dependencies
