LIB        = libwww.a

SRCS       = \
         HtmlTypes.hs\
	 HtmlClasses.hs\
	 HtmlKernel.hs\
	 HtmlList.hs\
	 HtmlBlock.hs\
	 HtmlText.hs\
	 HtmlLink.hs\
	 HtmlMeta.hs\
	 HtmlForm.hs\
	 HtmlApplet.hs\
	 HtmlTable.hs\
	 HtmlFrame.hs\
	 Html.hs\
	 TableGen.hs

SUBDIRS = test

include top/mk/boilerplate.mk
