LIB        = libconcurrency.a

SRCS       = Thread.hs\
             ThreadWait.hs\
             Variable.hs\
	     Lock.hs\
             BSem.hs\
	     QSem.hs\
	     Mutex.hs\
	     RVar.hs\
	     Event.hs\
	     Selective.hs\
	     SAP.hs\
	     Future.hs\
	     Concurrency.hs\
             Toggle.hs\
             PrimEvent.hs\
             BaseEvent.hs\
             TwoWayChannel.hs\
             IOtoBaseEvent.hs\
             EV.hs\
             Channels.hs\
             FileEV.hs\
             SocketEV.hs\


SUBDIRS = test server

include top/mk/boilerplate.mk
