LIBS = $(UNIDIR)/reactor/libreactor.a $(UNIDIR)/concurrency/libconcurrency.a\
   $(UNIDIR)/util/libutil.a

SRCS = Test0.hs Test1.hs Test10.hs Test2.hs Test3.hs Test4.hs Test5.hs Test6.hs Test7.hs Test8.hs Test9.hs TestRegularExpression.hs TestNotification.hs
# Test11.hs isn't a self-contained test program.
include top/mk/boilerplate.mk
