LIBS = top/concurrency/libconcurrency.a top/util/libutil.a

SRCS = Test0.hs Test1.hs Test2.hs Test4.hs Test5.hs Test6.hs Test7.hs Test8.hs Test9.hs Test10.hs Testm.hs Test12.hs
# Test3.hs is obsolete

include top/mk/boilerplate.mk
