LIBS = top/concurrency/libconcurrency.a top/util/libutil.a

SRCS = Test0.hs Test1.hs Test2.hs Test4.hs Test5.hs Test6.hs Test7.hs Test8.hs Test9.hs Test10.hs Testm.hs Test12.hs
# Test3.hs is obsolete

include top/mk/boilerplate.mk
# DO NOT DELETE: Beginning of Haskell dependencies
Test0.o : Test0.hs
Test0.o : top/concurrency/Concurrency.hi
Test0.o : top/util/Dynamics.hi
Test0.o : top/util/Debug.hi
Test1.o : Test1.hs
Test1.o : top/concurrency/Concurrency.hi
Test1.o : top/util/Dynamics.hi
Test1.o : top/util/Debug.hi
Test2.o : Test2.hs
Test2.o : top/concurrency/Concurrency.hi
Test2.o : top/concurrency/RVar.hi
Test2.o : top/util/Debug.hi
Test3.o : Test3.hs
Test3.o : top/concurrency/Concurrency.hi
Test3.o : top/util/Object.hi
Test3.o : top/util/Debug.hi
Test4.o : Test4.hs
Test4.o : top/concurrency/Concurrency.hi
Test4.o : top/util/Debug.hi
Test5.o : Test5.hs
Test5.o : top/concurrency/Concurrency.hi
Test5.o : top/util/Debug.hi
Test6.o : Test6.hs
Test6.o : top/concurrency/Thread.hi
Test6.o : top/concurrency/Variable.hi
Test6.o : top/util/Queue.hi
Test6.o : top/util/Debug.hi
Test7.o : Test7.hs
Test7.o : top/concurrency/Concurrency.hi
Test7.o : top/util/Debug.hi
Test8.o : Test8.hs
Test8.o : top/concurrency/Concurrency.hi
Test8.o : top/concurrency/Mutex.hi
Test8.o : top/concurrency/Variable.hi
Test8.o : top/util/Debug.hi
Test9.o : Test9.hs
Test9.o : top/concurrency/Concurrency.hi
Test9.o : top/util/Dynamics.hi
Test9.o : top/util/Debug.hi
Test10.o : Test10.hs
Test10.o : top/concurrency/Selective.hi
Testm.o : Testm.hs
Testm.o : top/concurrency/Concurrency.hi
Testm.o : top/util/Dynamics.hi
Testm.o : top/util/Debug.hi
Test12.o : Test12.hs
Test12.o : top/concurrency/Concurrency.hi
Test12.o : top/concurrency/RVar.hi
Test12.o : top/concurrency/Mutex.hi
Test12.o : top/util/Queue.hi
Test12.o : top/util/Maybes.hi
Test12.o : top/util/Debug.hi
# DO NOT DELETE: End of Haskell dependencies
