LIB        = libgraphs.a
SRCS       = Graph.hs SharedGraph.hs SharedGraphService.hs \
   SharedGraphClient.hs GraphDisp.hs DaVinciGraphDisp.hs
SUBDIRS    = 

XHCDIRS = $(HTKDIRS)

include top/mk/boilerplate.mk








