LIB        = libgraphs.a
# SRCS       = Graph.hs SharedGraph.hs SharedGraphService.hs \
#   SharedGraphClient.hs GraphDisp.hs
SRCS       = GraphDisp.hs GraphConfigure.hs NewNames.hs Graph.hs \
   SimpleGraph.hs GetAttributes.hs DisplayGraph.hs
SUBDIRS    = test

XHCDIRS = $(HTKDIRS)

include top/mk/boilerplate.mk








