LIBS = $(UNIDIR)/graphs/libgraphs.a $(UNIDIR)/htk/libhtk.a \
   $(UNIDIR)/reactor/libreactor.a $(UNIDIR)/server/libserver.a \
   $(UNIDIR)/concurrency/libconcurrency.a $(UNIDIR)/util/libutil.a
LIB        = libgraphs.a
SRCS       = GraphDisp.hs GraphConfigure.hs NewNames.hs Graph.hs \
   SimpleGraph.hs GetAttributes.hs DisplayGraph.hs GraphEditor.hs \
   GraphEditorService.hs MainGraphEditorServer.hs GraphEditorRemote.hs
SUBDIRS    = test

XHCDIRS = $(HTKDIRS)

include top/mk/boilerplate.mk

