LIBS = $(UNIDIR)/cvs/libcvs.a $(UNIDIR)/reactor/libreactor.a\
   $(UNIDIR)/concurrency/libconcurrency.a $(UNIDIR)/util/libutil.a
SRCS = Mainallocate.hs Maintestallocate.hs

include top/mk/boilerplate.mk
