# NB.  Although this package is contained in the MMiSS directory, it should
# be compiled before it; this is done by getting the main uni Makefile
# to refer to it directly.
PACKAGES = uni-mmiss uni-mmiss-parser

SRCS =  TestShort.hs TestAST.hs TestLaTeX.hs

include /home/amahnke/uni/mk/boilerplate.mk
