LIBS = $(UNIDIR)/graphs/libgraphs.a $(UNIDIR)/davinci/libdavinci.a \
   $(UNIDIR)/htk/libhtk.a $(UNIDIR)/reactor/libreactor.a \
   $(UNIDIR)/concurrency/libconcurrency.a $(UNIDIR)/util/libutil.a

LIB = libtestgraph.a

SRCS = GraphDispTest.hs TestDaVinci.hs

XHCDIRS= $(HTKDIRS)

include top/mk/boilerplate.mk


