LIBS = $(UNIDIR)/graphs/libgraphs.a $(UNIDIR)/htk/libhtk.a \
   $(UNIDIR)/reactor/libreactor.a $(UNIDIR)/concurrency/libconcurrency.a \
   $(UNIDIR)/util/libutil.a

LIB = libtestgraph.a

SRCS = GraphDispTest.hs TopSort.hs Hasse.hs DrawDepend.hs \
   TestGetAttributes.hs TestGetAttributes2.hs

XHCDIRS= $(HTKDIRS)

include top/mk/boilerplate.mk


