LIB        = libtools.a

SRCS       = \
         WB.hs\
         Diff.hs\
	 Dvips.hs\
	 Grep.hs\
	 HolCSP.hs\
	 HolZ.hs\
	 HugsIntrp.hs\
	 Hugs.hs\
	 Latex.hs\
	 Moby.hs\
	 Tas.hs\
	 TextEdit.hs\
	 XDvi.hs\

SUBDIRS = test

XHCDIRS = $(HTKDIRS)

include top/mk/boilerplate.mk
