LIBS = $(UNIDIR)/davinci/libdavinci.a $(UNIDIR)/graphs/test/libtestgraph.a \
   $(UNIDIR)/graphs/libgraphs.a $(UNIDIR)/htk/libhtk.a \
   $(UNIDIR)/reactor/libreactor.a $(UNIDIR)/concurrency/libconcurrency.a \
   $(UNIDIR)/util/libutil.a

SRCS = TestDaVinci.hs MainDepend.hs TestGraphEditor.hs TestGraphEditor2.hs TestDaVinciDouble.hs

XHCDIRS= $(UNIDIR)/graphs/test:$(HTKDIRS)

include top/mk/boilerplate.mk


