./canvasitems/Arc.hs
./canvasitems/CanvasItem.hs
./canvasitems/CanvasItemAux.hs
./canvasitems/CanvasTag.hs
./canvasitems/EmbeddedCanvasWin.hs
./canvasitems/ImageItem.hs
./canvasitems/Line.hs
./canvasitems/Oval.hs
./canvasitems/Polygon.hs
./canvasitems/Rectangle.hs
./canvasitems/TextItem.hs
./canvasitems/BitMapItem.hs
./components/ICursor.hs
./components/Icon.hs
./components/Image.hs
./components/Index.hs
./components/Selection.hs
./components/Slider.hs
./components/BitMap.hs
./containers/Box.hs
./containers/Frame.hs
./containers/Window.hs
./containers/Toplevel.hs
./containers/Packer.hs
./devices/Bell.hs
./devices/Printer.hs
./devices/Screen.hs
./devices/XSelection.hs
./devices/Mouse.hs
./devices/Keyboard.hs
./kernel/GUIMethods.hs
./kernel/GUIObject.hs
./kernel/GUIObjectKind.hs
./kernel/GUIObjectName.hs
./kernel/GUIState.hs
./kernel/GUICore.hs
./kernel/GUIBaseClasses.hs
./kernel/GUIWish.hs
./kernel/GUIInteraction.hs
./kernel/GUIRealise.hs
./menuitems/Indicator.hs
./menuitems/Menu.hs
./menuitems/MenuButton.hs
./menuitems/PulldownMenu.hs
./menuitems/RadioButton.hs
./menuitems/Separator.hs
./menuitems/MenuItem.hs
./menuitems/Button.hs
./menuitems/CheckButton.hs
./resources/Colour.hs
./resources/Cursor.hs
./resources/Font.hs
./resources/GUIEvent.hs
./resources/GUIValue.hs
./resources/Resources.hs
./resources/Geometry.hs
./test/Test0.hs
./test/Test1.hs
./test/Test2.hs
./test/Test3.hs
./test/Test4.hs
./test/Test5.hs
./test/Test6.hs
./test/Test7.hs
./test/TestUtil.hs
./test/Counter.hs
./test/Test8.hs
./test/Test9.hs
./textitems/Mark.hs
./textitems/TextTag.hs
./textitems/EmbeddedTextWin.hs
./toolkit/IconBar.hs
./toolkit/InputForm.hs
./toolkit/LabelBox.hs
./toolkit/LogWin.hs
./toolkit/MatrixBox.hs
./toolkit/ModalDialog.hs
./toolkit/Prompt.hs
./toolkit/PromptWin.hs
./toolkit/RadioGroup.hs
./toolkit/ScrollBox.hs
./toolkit/SelectBox.hs
./toolkit/InputWin.hs
./toolkit/ComboBox.hs
./toolkit/SpinButton.hs
./toolkit/DialogWin.hs
./toplevel/HTk.hs
./toplevel/GUIIntrinsics.hs
./widgets/Editor.hs
./widgets/Entry.hs
./widgets/Label.hs
./widgets/Message.hs
./widgets/OptionMenu.hs
./widgets/ScrollBar.hs
./widgets/Space.hs
./widgets/ListBox.hs
./widgets/Canvas.hs
./widgets/Scale.hs
./a.hs
import Debug(debug)
