LIBS       = $(HTKDIR)/libhtk.a\
             $(REACTORDIR)/libreactor.a\
	     $(CONCDIR)/libconcurrency.a\
	     $(UTILDIR)/libutil.a

SRCS       = Mainblobs.hs MaincanvasEx.hs Mainhello1.hs Mainhello2.hs Mainhello3.hs MainlistEx.hs MainmenuEx.hs MainreliefEx.hs MaintestWidEx.hs MainxmasCanvas.hs 

include top/mk/boilerplate.mk



