LIBS = top/htk/libhtk.a top/reactor/libreactor.a\
   top/concurrency/libconcurrency.a top/util/libutil.a

SRCS       = Mainblobs.hs MaincanvasEx.hs Mainhello1.hs Mainhello2.hs Mainhello3.hs MainlistEx.hs MainmenuEx.hs MainreliefEx.hs MaintestWidEx.hs MainxmasCanvas.hs 

include top/mk/boilerplate.mk



